Added FollowTle and Tracking instructions
daleghent/nina-planewave-tools pull request #2
Opened 2023-06-11 14:25 UTC by NickHardy

Hi Dale,
I have added some instructions.
- Follow TLE
- Set Tracking
Please let me know what you think.

2023-06-12 18:33 UTC, daleghent requested changes

2023-06-12 18:33 UTC, daleghent commented on Tracking/Tracking.cs
> +        public IList<short> M3Ports => ItemLists.M3Ports;
This doesn't appear to be used anywhere

2023-06-12 18:33 UTC, daleghent commented on Tracking/Tracking.cs
> +    [ExportMetadata("Name", "Set tracking")]
Capitalize the T - `Set Tracking`

2023-06-12 18:33 UTC, daleghent commented on Tracking/Tracking.cs
> +    [ExportMetadata("Category", "PlaneWave Tools")]
I wonder if this `Set Tracking` instruction should be placed into its own category with `TLE Follow` (or `Load TLE` in its alternate name) - perhaps something like `PlaneWave Tools - Satellites`

2023-06-12 18:33 UTC, daleghent commented on TLE/TLEControl.cs
> +    [ExportMetadata("Name", "TLE follow")]
Perhaps this should be named `Load TLE` since that's what this is doing with PWI4?

2023-06-12 18:33 UTC, daleghent commented on TLE/TLEControl.cs
> +    [ExportMetadata("Category", "PlaneWave Tools")]
See comment regarding Category name that I made in `Tracking.cs`

2023-06-12 18:33 UTC, daleghent commented on TLE/TLEControl.cs
> +                        throw new SequenceEntityFailedException("Timed out after 1 minute.");
Timed out doing what?

2023-06-12 20:52 UTC, NickHardy commented on Tracking/Tracking.cs
> +        public IList<short> M3Ports => ItemLists.M3Ports;
Oops. I took it out now.

2023-06-12 20:52 UTC, NickHardy commented on Tracking/Tracking.cs
> +    [ExportMetadata("Name", "Set tracking")]
Done

2023-06-12 20:53 UTC, NickHardy commented on Tracking/Tracking.cs
> +    [ExportMetadata("Category", "PlaneWave Tools")]
Set Tracking is just like the normal Set Tracking instruction but only the on and off options.

2023-06-12 20:54 UTC, NickHardy commented on TLE/TLEControl.cs
> +    [ExportMetadata("Name", "TLE follow")]
It starts following and tracking right away.

2023-06-12 20:54 UTC, NickHardy commented on TLE/TLEControl.cs
> +    [ExportMetadata("Category", "PlaneWave Tools")]
Might not be needed

2023-06-12 20:56 UTC, NickHardy commented on TLE/TLEControl.cs
> +                        throw new SequenceEntityFailedException("Timed out after 1 minute.");
Failed to follow the target within a minute. Throw an error and stop tracking to be on the safe side.
I did improve the message a bit.

2023-06-12 20:57 UTC, NickHardy commented
Hi Dale,
I will test the normal Set Tracking instruction on a real scope to see if it's working or not.
Feel free to wait before merging.

2023-07-04 18:53 UTC, daleghent approved these changes

2023-07-04 18:54 UTC, merged